config/routes.rb
Rails.application.routes.draw do

  # 顧客用
# /customers/sign_in ...
  devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  
# 管理者用
# /admin/sign_in ...
devise_for :admin,skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  
  root to: 'public/homes#top'
  get "/home/about" => "public/homes#about"

  get "/item/index" => "public/items#index"
  get "/item/:id" => "public/items#show", as: 'show'
  
  get "/customer/show" => "public/customers#show"
  get "/customer/edit" => "public/customers#edit"
  patch "/customer" => "public/customers#update"
  get "/customer/unsubscribe" => "public/customers#unsubscribe"
  patch "/customer/withdraw" => "public/customers#withdraw"
  
  get "/addresses" => "public/addresses#index"
  get "/address/:id/edit" => "public/addresses#edit", as: 'adderess_edit'
  post "/addresses" => "public/addresses#create", as: 'adderess_create'
  patch "/address/:id" => "public/addresses#update", as: 'adderess_update'
  delete "/address/:id" => "public/addresses#destroy", as: 'adderess_destroy'
  
  get "/cart_items" => "public/cart_items#index"
  post "/cart_items" => "public/cart_items#create"
  patch "/cart_item/:id" => "public/cart_items#update"
  delete "/cart_item/:id" => "public/cart_items#destroy", as: 'destroy'
  delete "/cart_items/destroy_all" => "public/cart_items#destroy_all",as: 'all_destroy'
  
  get "/orders/new" => "public/orders#new"
  post "/orders/comfirm" => "public/orders#comfirm"
  get "/orders/complete" => "public/orders#complete"
  post "/orders" => "public/orders#create"
  get "/orders" => "public/orders#index", as: 'order_index'
  get "/order/:id" => "public/orders#show", as: 'order_show'
  
#namespaceをつけるとURLに名前を付けることができる
  namespace :admin do
  root to: 'homes#top'
  resources :items, only: [:new, :create, :index, :show, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :orders, only: [:show, :update]
  resources :order_details, only: [:update]
end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    def full_address
     '〒' + postal_code + ' ' + address + ' ' + name
    end
    
    belongs_to :customer

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    
 belongs_to :customer
 belongs_to :item
 
 def subtotal
    item.with_tax_price * amount
 end
 

 
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  
  has_many :orders
  
  has_many :cart_items
  
  has_many :addresses
  
  def customer_infomation
    self.postal_code + self.address + self.last_name + self.first_name
    #データ型変更の場合はto_iやto_sを使用
  end
  
  def full_name
    self.last_name + self.first_name
    #データ型変更の場合はto_iやto_sを使用
  end
  
  def full_address
     postal_code + address
  end
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
end

app/models/genre.rb
class Genre < ApplicationRecord
    
    enum name_id: { 登録済ジャンルから選択: 0}#integer型で管理する
end

app/models/item.rb
class Item < ApplicationRecord
    
  attachment :image
  has_many :cart_items
  has_many :order_details
  
  
  
  enum is_active: { 販売中: true, 販売停止中: false}
  
  def with_tax_price
    (price * 1.1).floor
  end
  
  def shipping_cost
   "800"
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
    
    enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
    
    enum address_id: { ご自身の住所: 0, 登録済住所から選択: 1, 新しいお届け先: 2 }
    
    enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}
    
    belongs_to :customer
    has_many :order_details
    accepts_nested_attributes_for :order_details
    
   def subtotal
    item.with_tax_price * amount
   end
    
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    
    belongs_to :order
    belongs_to :item
    
    enum making_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}
    
   def subtotal
    item.with_tax_price * amount
   end
   
end

app/controllers/admin/genres_controller.rb
class Admin::GenresController < ApplicationController
    
  def index
    @genres = Genre.all
  end
  
  def create
    @genres = Genre.new(genre_params)
    @genres.save
    redirect_to admin_genres_path
  end
  
  def edit
    @genre = Genre.find(params[:id])
  end
  
  def update
    @genre = Genre.find(params[:id])
    @genre.update(genre_params)
    redirect_to admin_genres_path
  end
  
  def genre_params
    params.require(:genre).permit(:name)
  end

end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    
  def top
   @order = Order.all
   @cart_items = CartItem.all
  end
end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
    
  def new
    @item = Item.new
    @genre = Genre.all
  end

  def create
    @item = Item.new(item_params)
    @item.save
    redirect_to admin_items_path
  end

  def index
    @items = Item.all
    if params[:is_active] == true
      @items.is_active = "販売中"
      
    elsif params[:is_active] == false
      @items.is_active = "販売停止中"
    end
  end

  def show
    @item = Item.find(params[:id])
    if params[:is_active] == true
      @items.is_active = "販売中"
    
    elsif params[:is_active] == false
      @items.is_active = "販売停止中"
    end
  end

  def edit
    @item = Item.find(params[:id])
  end
  
  def update
    @item = Item.find(params[:id])
    @item.update(item_params)
    redirect_to admin_items_path
  end
  
  private

  def item_params
    params.require(:item).permit(:name, :image, :introduction, :price, :is_active)
  end
  
end

app/controllers/admin/orders_controller.rb
class Admin::OrdersController < ApplicationController
    
 def show
  @order = Order.find(params[:id])
  @order_details = @order.order_details
 end
 
 def update
  @order = Order.find(params[:id])
  @order.update!(order_params)
  @order_details = @order.order_details
  if params[:order][:status] == "製作中"
   @order_details.each do |order_detail|
    order_detail.making_status = "製作中"
    order_detail.save
  end
 end
  redirect_to request.referer
 end
 
 private
   def order_params
    params.require(:order).permit(:payment_method, :postal_code, :address, :name, :total_payment, :shipping_cost, :status, :product_status)
   end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_up_path_for(resource)
  case resource
  when Customer
    root_path
    
  when Admin
    admin_root_path
  end
end

def after_sign_in_path_for(resource)
  case resource
  when Customer
    root_path
    
  when Admin
    admin_root_path
  end
end

  protected

#email以外のsign up情報を保存する
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def top
  end

  def about
  end
end 
    

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/order_details_helper.rb
module Admin::OrderDetailsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/items/create.html.erb
<h1>商品投稿フォーム</h1>
<%= form_with model: @item, url: admin_items_path, local:true do |f| %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>
   <h4>商品名</h4>
    <%= f.text_field :name %>
  <h4>説明</h4>
   <%= f.text_area :introduction %>
  
  <div>
  <h4>ジャンル選択</h4>
  <%= form_with model:@genre, url:admin_items_path, method: :patch, local:true do |f| %>
   <%= f.label :name_id, Genre.name_ids_i18n[:登録済ジャンルから選択] %></br>
   <%= f.select :name_id, options_from_collection_for_select(Genre.all, :id, :name) %>
  </div>
  
  <% end %>
   <h4>値段</h4>
   <%= f.text_area :price %></br>
  
   <h4>販売ステータス</h4>
   <%= f.radio_button :is_active, "販売中" %>
   <%= f.label :is_active, "販売中" %>

   <%= f.radio_button :is_active, "販売停止中" %>
   <%= f.label :is_active, "販売停止中" %></br>
   <%= f.submit '投稿' %>
<% end %>

app/views/admin/items/edit.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">
    <h2>商品編集</h2>
<%= form_with model:@item, url:"/admin/items/#{@item.id}", method: :patch, local:true do |f| %>

　<label for="inputName">商品イメージ</label>
  <%= f.attachment_field :image %><br>

  <label for="inputName">商品名</label>
  <%= f.text_field :name, autofocus: true, id:"inputName", placeholder:"商品名"%><br>
  
  <label for="inputName">説明</label>
  <%= f.text_field :introduction, autofocus: true, id:"inputName", placeholder:"説明"%><br>
  
  <label for="inputName">値段</label>
  <%= f.number_field :price, autofocus: true, id:"inputPrice", placeholder:"値段"%><br>
  
  <%= f.radio_button :is_active, "販売中" %>
  <%= f.label :is_active, "販売中" %>

  <%= f.radio_button :is_active, "販売停止中" %>
  <%= f.label :is_active, "販売停止中" %></br>
  
  <%= f.submit "変更を保存" %><br>
  
  
  
  
<% end %>

app/views/admin/items/index.html.erb
<% @items.each do |item| %>
 <div>
  <%= link_to admin_item_path(item.id) do %>
  <%= attachment_image_tag item, :image %>
  <% end %>
  <p>アイテム名：<%= item.name %></p>
  <p>説明：<%= item.introduction %></p>
  <p>値段：<%= item.price %></p>
  <p>販売ステータス：<%= item.is_active %></p>
</div>
<% end %>

app/views/admin/items/new.html.erb
<h1>商品投稿フォーム</h1>
<%= form_with model: @item, url: admin_items_path, method: :post, local:true do |f| %>
  <h4>画像</h4>
  <%= f.attachment_field :image %>
   <h4>商品名</h4>
    <%= f.text_field :name %>
  <h4>説明</h4>
   <%= f.text_area :introduction %>
  
  <div>
  <h4>ジャンル選択</h4>
  <%= form_with model:@genre, url: admin_items_path, method: :post, local:true do |f| %>
   <%#= f.label :name_id, Genre.name_ids_i18n[:登録済ジャンルから選択] %>
   <%= f.select :name_id, options_from_collection_for_select(Genre.all, :id, :name) %>
  </div>
  
   <h4>値段</h4>
   <%= f.text_field :price %></br>
  
   <h4>販売ステータス</h4>
   <%= f.radio_button :is_active, "販売中" %>
   <%= f.label :is_active, "販売中" %>

   <%= f.radio_button :is_active, "販売停止中" %>
   <%= f.label :is_active, "販売停止中" %></br>
   <%= f.submit '投稿' %>
<% end %>
<% end %>

app/views/admin/items/show.html.erb
<div class="row">
  <div class="col-sm-12 col-md-8 col-lg-5 px-5 px-sm-0 mx-auto">

   <p>アイテム名：<%= @item.name %></p>
   <p>説明：<%= @item.introduction %></p>
   <p>値段：<%= @item.price %></p>
   <p>販売ステータス：<%= @item.is_active %></p>
   

   <%= link_to "編集", edit_admin_item_path, class: 'nav-link text-dark' %>
  </div>
</div>

app/views/items/about.html.erb
<main>
 <p id="notice"></p>
  <div class="container">
   <div class="row">
    <h1 class="px-3 mx-auto">ようこそ <i class="fas fa-book"></i><strong>長野CAKEへ!!</strong>!</h1>
   </div>
  </div>
</main>
<footer>
 <div class="container mt-5">
  <div class="row">
   <div class="mx-auto">
   </div>
  </div>
 </div>
</footer>

app/views/items/top.html.erb
<h1>トップページ</h1>