config/routes.rb
Rails.application.routes.draw do

  # 顧客用
# /customers/sign_in ...
  devise_for :customers,skip: [:passwords,], controllers: {
  registrations: "public/registrations",
  sessions: 'public/sessions'
}
  
# 管理者用
# /admin/sign_in ...
devise_for :admin,skip: [:registrations, :passwords] ,controllers: {
  sessions: "admin/sessions"
}
  
  root to: 'public/homes#top'
  get "/home/about" => "public/homes#about"

  get "/item/index" => "public/items#index"
  get "/item/:id" => "public/items#show", as: 'show'
  
  get "/customer/show" => "public/customers#show"
  get "/customer/edit" => "public/customers#edit"
  patch "/customer" => "public/customers#update"
  get "/customer/unsubscribe" => "public/customers#unsubscribe"
  patch "/customer/withdraw" => "public/customers#withdraw"
  
  get "/addresses" => "public/addresses#index"
  get "/address/:id/edit" => "public/addresses#edit", as: 'adderess_edit'
  post "/addresses" => "public/addresses#create", as: 'adderess_create'
  patch "/address/:id" => "public/addresses#update", as: 'adderess_update'
  delete "/address/:id" => "public/addresses#destroy", as: 'adderess_destroy'
  
  get "/cart_items" => "public/cart_items#index"
  post "/cart_items" => "public/cart_items#create"
  patch "/cart_item/:id" => "public/cart_items#update"
  delete "/cart_item/:id" => "public/cart_items#destroy", as: 'destroy'
  delete "/cart_items/destroy_all" => "public/cart_items#destroy_all",as: 'all_destroy'
  
  get "/orders/new" => "public/orders#new"
  post "/orders/comfirm" => "public/orders#comfirm"
  get "/orders/complete" => "public/orders#complete"
  post "/orders" => "public/orders#create"
  get "/orders" => "public/orders#index", as: 'order_index'
  get "/order/:id" => "public/orders#show", as: 'order_show'
  
#namespaceをつけるとURLに名前を付けることができる
  namespace :admin do
  root to: 'homes#top'
  resources :items, only: [:new, :create, :index, :show, :edit, :update]
  resources :customers, only: [:index, :show, :edit, :update]
  resources :genres, only: [:index, :create, :edit, :update]
  resources :orders, only: [:show, :update]
  resources :order_details, only: [:update]
end
  
  
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/address.rb
class Address < ApplicationRecord
    def full_address
     '〒' + postal_code + ' ' + address + ' ' + name
    end
    
    belongs_to :customer

end

app/models/admin.rb
class Admin < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart_item.rb
class CartItem < ApplicationRecord
    
 belongs_to :customer
 belongs_to :item
 
 def subtotal
    item.with_tax_price * amount
 end
 

 
end

app/models/customer.rb
class Customer < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  
  
  has_many :orders
  
  has_many :cart_items
  
  has_many :addresses
  
  def customer_infomation
    self.postal_code + self.address + self.last_name + self.first_name
    #データ型変更の場合はto_iやto_sを使用
  end
  
  def full_name
    self.last_name + self.first_name
    #データ型変更の場合はto_iやto_sを使用
  end
  
  def full_address
     postal_code + address
  end
  

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         
  
end

app/models/genre.rb
class Genre < ApplicationRecord
    
    enum name_id: { 登録済ジャンルから選択: 0}#integer型で管理する
end

app/models/item.rb
class Item < ApplicationRecord
    
  attachment :image
  has_many :cart_items
  has_many :order_details
  
  
  
  enum is_active: { 販売中: true, 販売停止中: false}
  
  def with_tax_price
    (price * 1.1).floor
  end
  
  def shipping_cost
   "800"
  end
  
end

app/models/order.rb
class Order < ApplicationRecord
    
    enum payment_method: { クレジットカード: 0, 銀行振込: 1 }
    
    enum address_id: { ご自身の住所: 0, 登録済住所から選択: 1, 新しいお届け先: 2 }
    
    enum status: { 入金待ち: 0, 入金確認: 1, 製作中: 2, 発送準備中: 3, 発送済み: 4}
    
    belongs_to :customer
    has_many :order_details
    accepts_nested_attributes_for :order_details
    
   def subtotal
    item.with_tax_price * amount
   end
    
end

app/models/order_detail.rb
class OrderDetail < ApplicationRecord
    
    belongs_to :order
    belongs_to :item
    
    enum making_status: { 着手不可: 0, 製作待ち: 1, 製作中: 2, 製作完了: 3}
    
   def subtotal
    item.with_tax_price * amount
   end
   
end

app/controllers/admin/homes_controller.rb
class Admin::HomesController < ApplicationController
    
  def top
   @order = Order.all
   @cart_items = CartItem.all
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
before_action :configure_permitted_parameters, if: :devise_controller?

def after_sign_up_path_for(resource)
  case resource
  when Customer
    root_path
    
  when Admin
    admin_root_path
  end
end

def after_sign_in_path_for(resource)
  case resource
  when Customer
    root_path
    
  when Admin
    admin_root_path
  end
end

  protected

#email以外のsign up情報を保存する
  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:last_name, :first_name, :last_name_kana, :first_name_kana, :postal_code, :address, :telephone_number])
  end
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def top
  end

  def about
  end
end 
    

app/helpers/admin/customers_helper.rb
module Admin::CustomersHelper
end

app/helpers/admin/genres_helper.rb
module Admin::GenresHelper
end

app/helpers/admin/homes_helper.rb
module Admin::HomesHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/admin/orders_helper.rb
module Admin::OrdersHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/homes_helper.rb
module HomesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/shared/_error_messages.html.erb
<% if resource.errors.any? %>
  <div id="error_explanation">
    <h2>
      <%= I18n.t("errors.messages.not_saved",
                 count: resource.errors.count,
                 resource: resource.class.model_name.human.downcase)
       %>
    </h2>
    <ul>
      <% resource.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
    </ul>
  </div>
<% end %>

app/views/admin/shared/_links.html.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Log in", new_session_path(resource_name) %><br />
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>NaganoCake</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

 <body class="d-flex flex-column vh-100">
    <header class="shadow-sm">
      <nav class="navbar navbar-expand-lg navbar-light">
        <div class="container">
          <a class="navbar-brand p-3" href="/"><%= image_tag('nagano cake (1)') %></a>
          <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
          </button>
          <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav ml-auto">
              
            <% if customer_signed_in? %>
    　　　　
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "マイページ", customer_show_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "商品一覧", item_index_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "カート一覧", cart_items_path, class: 'nav-link text-dark' %>
            </li>
            
            <% elsif admin_signed_in? %>
            <li class="nav-item">
              <%= link_to "ログアウト", destroy_customer_session_path, method: :delete, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to '商品投稿フォーム', new_admin_item_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to 'ジャンル投稿フォーム', admin_genres_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "会員一覧", admin_customers_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "商品一覧", admin_items_path, class: 'nav-link text-dark' %>
            </li>
        
            <% else %>
            <li class="nav-item">
              <%= link_to "新規登録", new_customer_registration_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "会社概要", home_about_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "ログイン", new_customer_session_path, class: 'nav-link text-dark' %>
            </li>
            <li class="nav-item">
              <%= link_to "商品一覧", item_index_path, class: 'nav-link text-dark' %>
            </li>
            <% end%>
            
            </ul>
          </div>
        </div>
      </nav>
    </header>
    <main class="mb-auto">
    <%= yield %>
    </main>
    <footer class="bg-dark text-white pt-5 pb-4">
      <div class="container">
        <div class="row no-gutters">
          <div class="col-md-4">
            <%= image_tag('名称未設定のデザイン') %>
        </div>
      </div>
    </footer>
  </body>
</html>